name: AuthTotal
version: '${project.version}'
main: org.goyda.authtotal.AuthTotal
api-version: '1.19'
commands:
  register:
    aliases:
      - reg
      - r
  login:
    aliases:
      - log
      - l