name: AuthTotal
version: '1.0'
main: org.goyda.authtotal.AuthTotal
api-version: '1.19'
permissions:
  authtotal.player.authorized:
    default: false
    description: "jopa"
commands:
  register:
    aliases:
      - reg
      - r
  login:
    aliases:
      - log
      - l